angular.module('projectDemo',['ui.router','angularCSS',
'projectDemo.homePage',
'projectDemo.classifyPage',
'projectDemo.musicPage',
'projectDemo.cartPage',
'projectDemo.minePage'])
.config(function($stateProvider,$urlRouterProvider){
  $urlRouterProvider.otherwise('/home')
})
